import type { CropCatalogueItem, BedTypeDefinition, FarmElementDefinition } from '../types/designer';

export const BED_TYPES_CATALOGUE: BedTypeDefinition[] = [
  {
    type: 'Raised Bed',
    name: 'Raised Bed',
    tagline: 'Deep root zone, superior aeration & weed control',
    defaultHeightMm: 350,
    defaultColor: '#d97706', // amber-600
    borderColor: '#92400e',
    icon: '🪴',
    waterRetention: 'Balanced',
    thermalMass: 'High',
    bestFor: 'Root crops, Nightshades, Leafy Greens',
    description: 'Elevated framed or mounded soil with rich compost. Prevents compaction and drains excess monsoon water.',
  },
  {
    type: 'Sunken Bed',
    name: 'Sunken Bed',
    tagline: 'Harvests runoff and stays cool in hot dry weather',
    defaultHeightMm: -200,
    defaultColor: '#0284c7', // sky-600
    borderColor: '#075985',
    icon: '🕳️',
    waterRetention: 'High',
    thermalMass: 'Normal',
    bestFor: 'Cucurbits, Melons, Summer Vegetables',
    description: 'Depressed planting trench that collects and traps precious rainwater in semi-arid summer microclimates.',
  },
  {
    type: 'Hot Bed',
    name: 'Hot Bed',
    tagline: 'Decomposing manure core warms winter seedlings',
    defaultHeightMm: 400,
    defaultColor: '#ea580c', // orange-600
    borderColor: '#9a3412',
    icon: '🔥',
    waterRetention: 'Balanced',
    thermalMass: 'High',
    bestFor: 'Winter nurseries, Early spring transplants',
    description: 'Layered with fresh cow dung and straw beneath rich loam to generate natural bottom heat.',
  },
  {
    type: 'Wicking Bed',
    name: 'Wicking Bed',
    tagline: 'Bottom-up water reservoir with minimal evaporation',
    defaultHeightMm: 450,
    defaultColor: '#0d9488', // teal-600
    borderColor: '#115e59',
    icon: '💧',
    waterRetention: 'High',
    thermalMass: 'Normal',
    bestFor: 'Herbs, High-value Vegetables, Water-sensitive species',
    description: 'Self-watering bed with a gravel water reservoir and overflow pipe underneath an organic geotextile membrane.',
  },
  {
    type: 'Hugelkultur Bed',
    name: 'Hugelkultur Bed',
    tagline: 'Decaying wood logs sponge moisture for years',
    defaultHeightMm: 600,
    defaultColor: '#65a30d', // lime-600
    borderColor: '#3f6212',
    icon: '🪵',
    waterRetention: 'High',
    thermalMass: 'High',
    bestFor: 'Squash, Gourds, Berry bushes, Heavy feeders',
    description: 'Permaculture mound built over decomposing tree logs and branches topped with manure and compost.',
  },
  {
    type: 'Keyhole Bed',
    name: 'Keyhole Bed',
    tagline: 'Central composting basket feeds circular bed',
    defaultHeightMm: 500,
    defaultColor: '#84cc16', // lime-500
    borderColor: '#4d7c0f',
    icon: '🗝️',
    waterRetention: 'High',
    thermalMass: 'High',
    bestFor: 'Kitchen gardens, Mixed greens, Companion guilds',
    description: 'Circular raised bed with a notch pathway leading to an active central vermicompost basket.',
  },
  {
    type: 'Terrace Bed',
    name: 'Terrace Bed',
    tagline: 'Step-levelled contours to stop slope erosion',
    defaultHeightMm: 300,
    defaultColor: '#78716c', // stone-500
    borderColor: '#44403c',
    icon: '⛰️',
    waterRetention: 'Balanced',
    thermalMass: 'Normal',
    bestFor: 'Sloped lands, Perennials, Root crops',
    description: 'Stepped soil bench supported by stone or vegetative bunds (Vetiver) along the slope contours.',
  },
  {
    type: 'Polyculture Bed',
    name: 'Polyculture Bed',
    tagline: 'Multi-tiered companion guild maximizing synergy',
    defaultHeightMm: 250,
    defaultColor: '#16a34a', // green-600
    borderColor: '#166534',
    icon: '🌈',
    waterRetention: 'High',
    thermalMass: 'Normal',
    bestFor: 'Multi-crop guilds (Tomato + Basil + Marigold)',
    description: 'Biodiverse bed combining tall crops, climbers, root crops, and insectary support plants.',
  },
  {
    type: 'Food Forest Patch',
    name: 'Food Forest Patch',
    tagline: '7-layer self-sustaining perennial ecosystem',
    defaultHeightMm: 150,
    defaultColor: '#15803d', // green-700
    borderColor: '#14532d',
    icon: '🌳',
    waterRetention: 'High',
    thermalMass: 'High',
    bestFor: 'Fruit trees, Berry shrubs, Perennial herbs, Tubers',
    description: 'Mimics natural forest edge dynamics with canopy trees, understory shrubs, herbaceous layer, and living mulch.',
  },
  {
    type: 'Nursery Bed',
    name: 'Nursery Bed',
    tagline: 'Fine sterile tilth for delicate seed germination',
    defaultHeightMm: 200,
    defaultColor: '#c084fc', // purple-400
    borderColor: '#7e22ce',
    icon: '🌱',
    waterRetention: 'Balanced',
    thermalMass: 'Normal',
    bestFor: 'Seedlings, Cuttings, Sapling propagation',
    description: 'Sheltered, finely sifted seedbed with Jeevamrit enrichment and shade net coverage for seedling production.',
  },
];

export const CROP_LIBRARY: CropCatalogueItem[] = [
  // ─── Vegetables ─────────────────────────────────────────────────────────────
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    scientificName: 'Solanum lycopersicum',
    spacingCm: 45,
    durationMonths: 4,
    color: '#ef4444',
    bgRgb: 'rgba(239, 68, 68, 0.15)',
    icon: '🍅',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Wicking Bed'],
    companionLikes: ['Tulsi', 'Basil', 'Marigold', 'Garlic', 'Carrot', 'Onion'],
    companionDislikes: ['Potato', 'Cabbage', 'Cauliflower', 'Fennel'],
    benefits: 'Heavy yielder, pairs exceptionally with Basil/Tulsi to repel hornworms.',
    description: 'Versatile nightshade fruit vegetable; thrives with stakes or trellis in rich compost.',
  },
  {
    id: 'chilli',
    name: 'Chilli',
    category: 'Vegetables',
    scientificName: 'Capsicum annuum',
    spacingCm: 40,
    durationMonths: 5,
    color: '#dc2626',
    bgRgb: 'rgba(220, 38, 38, 0.15)',
    icon: '🌶️',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Terrace Bed'],
    companionLikes: ['Tomato', 'Basil', 'Marigold', 'Onion', 'Carrot'],
    companionDislikes: ['Beans', 'Fennel'],
    benefits: 'Capsaicin naturally deters small chewing pests; great border intercrop.',
    description: 'High-value spice crop with sustained fruiting flush over multiple seasons.',
  },
  {
    id: 'brinjal',
    name: 'Brinjal (Eggplant)',
    category: 'Vegetables',
    scientificName: 'Solanum melongena',
    spacingCm: 60,
    durationMonths: 5,
    color: '#7e22ce',
    bgRgb: 'rgba(126, 34, 206, 0.15)',
    icon: '🍆',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Hugelkultur Bed'],
    companionLikes: ['Beans', 'Marigold', 'Mint', 'Peas', 'Tulsi'],
    companionDislikes: ['Fennel'],
    benefits: 'Sturdy bush, benefits from nitrogen fixation by bush beans planted around base.',
    description: 'Thrives in warm Chhattisgarh soils; heavy feeder needing organic mulch and Jeevamrit.',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    category: 'Vegetables',
    scientificName: 'Brassica oleracea var. capitata',
    spacingCm: 45,
    durationMonths: 3,
    color: '#22c55e',
    bgRgb: 'rgba(34, 197, 94, 0.15)',
    icon: '🥬',
    waterNeed: 'High',
    idealBedTypes: ['Raised Bed', 'Wicking Bed', 'Hot Bed'],
    companionLikes: ['Mint', 'Coriander', 'Onion', 'Garlic', 'Marigold'],
    companionDislikes: ['Tomato', 'Chilli', 'Brinjal', 'Mustard'],
    benefits: 'Mint and aromatic herbs mask cabbage scent from white butterflies.',
    description: 'Cool-season brassica forming dense leafy heads; requires consistent moisture.',
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'Vegetables',
    scientificName: 'Brassica oleracea var. botrytis',
    spacingCm: 45,
    durationMonths: 3,
    color: '#facc15',
    bgRgb: 'rgba(250, 204, 21, 0.15)',
    icon: '🥦',
    waterNeed: 'High',
    idealBedTypes: ['Raised Bed', 'Wicking Bed', 'Hot Bed'],
    companionLikes: ['Mint', 'Coriander', 'Garlic', 'Beans'],
    companionDislikes: ['Tomato', 'Chilli', 'Strawberries'],
    benefits: 'Benefited by aromatic border herbs to repel aphids and diamondback moths.',
    description: 'High-value winter crop forming prized white curds; sensitive to temperature swings.',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'Vegetables',
    scientificName: 'Daucus carota',
    spacingCm: 10,
    durationMonths: 3,
    color: '#f97316',
    bgRgb: 'rgba(249, 115, 22, 0.15)',
    icon: '🥕',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Sunken Bed', 'Wicking Bed'],
    companionLikes: ['Tomato', 'Chilli', 'Onion', 'Garlic', 'Radish'],
    companionDislikes: ['Dill', 'Fennel', 'Parsnip'],
    benefits: 'Deep taproot loosens compact soil; onion aroma deters carrot rust fly.',
    description: 'Requires loose, stone-free sandy loam or deep raised beds for straight sweet roots.',
  },
  {
    id: 'radish',
    name: 'Radish',
    category: 'Vegetables',
    scientificName: 'Raphanus sativus',
    spacingCm: 10,
    durationMonths: 1,
    color: '#f43f5e',
    bgRgb: 'rgba(244, 63, 94, 0.15)',
    icon: '🧅',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Keyhole Bed'],
    companionLikes: ['Tomato', 'Carrot', 'Cucumber', 'Pumpkin', 'Beans', 'Peas'],
    companionDislikes: ['Hyssop'],
    benefits: 'Fast 25-day catch crop; acts as trap crop for flea beetles away from cabbages.',
    description: 'Rapidly growing root vegetable, excellent intercrop between slow-growing perennials.',
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    scientificName: 'Solanum tuberosum',
    spacingCm: 30,
    durationMonths: 3,
    color: '#a16207',
    bgRgb: 'rgba(161, 98, 7, 0.15)',
    icon: '🥔',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Hugelkultur Bed', 'Terrace Bed'],
    companionLikes: ['Beans', 'Marigold', 'Corn', 'Garlic'],
    companionDislikes: ['Tomato', 'Cucumber', 'Pumpkin', 'Sunflower'],
    benefits: 'Thrives in loose compost mounds; Marigold deters root nematodes.',
    description: 'Major starchy tuber; needs frequent earthing up to prevent tuber greening.',
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'Vegetables',
    scientificName: 'Allium cepa',
    spacingCm: 15,
    durationMonths: 4,
    color: '#e11d48',
    bgRgb: 'rgba(225, 29, 72, 0.15)',
    icon: '🧅',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Sunken Bed', 'Terrace Bed'],
    companionLikes: ['Tomato', 'Carrot', 'Cabbage', 'Chilli', 'Strawberry'],
    companionDislikes: ['Beans', 'Peas', 'Asparagus'],
    benefits: 'Strong sulfur volatile scent masks companion crops from aphid and borer attacks.',
    description: 'Indispensable allium bulb; shallow-rooted, ideal edge companion in raised beds.',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    category: 'Vegetables',
    scientificName: 'Allium sativum',
    spacingCm: 12,
    durationMonths: 5,
    color: '#f8fafc',
    bgRgb: 'rgba(248, 250, 252, 0.2)',
    icon: '🧄',
    waterNeed: 'Low',
    idealBedTypes: ['Raised Bed', 'Terrace Bed', 'Keyhole Bed'],
    companionLikes: ['Tomato', 'Chilli', 'Brinjal', 'Carrot', 'Rose', 'Fruit Trees'],
    companionDislikes: ['Beans', 'Peas', 'Cabbage'],
    benefits: 'Natural antifungal and antibacterial root secretions protect nearby garden beds.',
    description: 'Potent companion bulb; planted along bed perimeters as a protective bio-barrier.',
  },
  {
    id: 'beans',
    name: 'Beans (French / Bush)',
    category: 'Vegetables',
    scientificName: 'Phaseolus vulgaris',
    spacingCm: 25,
    durationMonths: 2,
    color: '#16a34a',
    bgRgb: 'rgba(22, 163, 74, 0.15)',
    icon: '🫘',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Keyhole Bed'],
    companionLikes: ['Tomato', 'Brinjal', 'Cucumber', 'Carrot', 'Radish', 'Corn'],
    companionDislikes: ['Onion', 'Garlic', 'Chilli'],
    benefits: 'Rhizobium root nodules fix atmospheric nitrogen directly into the bed soil.',
    description: 'Heavy yielding legume that enriches the soil for surrounding heavy feeders.',
  },
  {
    id: 'peas',
    name: 'Peas',
    category: 'Vegetables',
    scientificName: 'Pisum sativum',
    spacingCm: 15,
    durationMonths: 3,
    color: '#4ade80',
    bgRgb: 'rgba(74, 222, 128, 0.15)',
    icon: '🫛',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Wicking Bed', 'Hot Bed'],
    companionLikes: ['Carrot', 'Radish', 'Cucumber', 'Beans', 'Mint'],
    companionDislikes: ['Onion', 'Garlic', 'Chilli'],
    benefits: 'Cool season nitrogen-fixer; climbing tendrils optimize vertical trellis space.',
    description: 'Sweet winter legume producing pods over 4–6 picking cycles.',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'Vegetables',
    scientificName: 'Cucumis sativus',
    spacingCm: 45,
    durationMonths: 3,
    color: '#059669',
    bgRgb: 'rgba(5, 150, 105, 0.15)',
    icon: '🥒',
    waterNeed: 'High',
    idealBedTypes: ['Sunken Bed', 'Hugelkultur Bed', 'Polyculture Bed'],
    companionLikes: ['Beans', 'Peas', 'Radish', 'Sunflower', 'Marigold'],
    companionDislikes: ['Potato', 'Aromatic Herbs'],
    benefits: 'Radish interplanted nearby repels cucumber beetles effectively.',
    description: 'Vigorous vining crop; benefits from trellis training or hugelkultur slopes.',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    category: 'Vegetables',
    scientificName: 'Cucurbita moschata',
    spacingCm: 120,
    durationMonths: 4,
    color: '#ea580c',
    bgRgb: 'rgba(234, 88, 12, 0.15)',
    icon: '🎃',
    waterNeed: 'Moderate',
    idealBedTypes: ['Hugelkultur Bed', 'Sunken Bed', 'Food Forest Patch'],
    companionLikes: ['Corn', 'Beans', 'Marigold', 'Radish'],
    companionDislikes: ['Potato'],
    benefits: 'Broad prickly leaves create living ground cover, shading soil and blocking weeds.',
    description: 'Classic member of the "Three Sisters" guild; heavy producer with long shelf life.',
  },
  {
    id: 'bottle_gourd',
    name: 'Bottle Gourd (Lauki)',
    category: 'Vegetables',
    scientificName: 'Lagenaria siceraria',
    spacingCm: 90,
    durationMonths: 4,
    color: '#84cc16',
    bgRgb: 'rgba(132, 204, 22, 0.15)',
    icon: '🍈',
    waterNeed: 'High',
    idealBedTypes: ['Hugelkultur Bed', 'Sunken Bed', 'Polyculture Bed'],
    companionLikes: ['Corn', 'Marigold', 'Beans', 'Radish'],
    companionDislikes: ['Potato'],
    benefits: 'Vigorous climber that creates overhead shade canopies on mandap/trellis structures.',
    description: 'Popular staple climber in Chhattisgarh farming; produces heavy nutritious gourds.',
  },
  {
    id: 'bitter_gourd',
    name: 'Bitter Gourd (Karela)',
    category: 'Vegetables',
    scientificName: 'Momordica charantia',
    spacingCm: 80,
    durationMonths: 4,
    color: '#15803d',
    bgRgb: 'rgba(21, 128, 61, 0.15)',
    icon: '🥒',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed'],
    companionLikes: ['Beans', 'Peas', 'Corn', 'Marigold'],
    companionDislikes: ['Potato'],
    benefits: 'Natural bitterness wards off common chewing pests; climbs mandap easily.',
    description: 'Medicinal and culinary staple; rich in antioxidants and blood sugar balancing charantin.',
  },
  {
    id: 'sweet_corn',
    name: 'Sweet Corn (Makka)',
    category: 'Vegetables',
    scientificName: 'Zea mays',
    spacingCm: 30,
    durationMonths: 3,
    color: '#eab308',
    bgRgb: 'rgba(234, 179, 8, 0.15)',
    icon: '🌽',
    waterNeed: 'High',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Sunken Bed'],
    companionLikes: ['Beans', 'Pumpkin', 'Cucumber', 'Melons'],
    companionDislikes: ['Tomato'],
    benefits: 'Provides natural physical trellis pole for climbing beans in Three Sisters guilds.',
    description: 'Tall heavy feeder that creates wind sheltered microclimates for delicate understory crops.',
  },
  {
    id: 'capsicum',
    name: 'Capsicum / Bell Pepper (Shimla Mirch)',
    category: 'Vegetables',
    scientificName: 'Capsicum annuum var. grossum',
    spacingCm: 45,
    durationMonths: 4,
    color: '#16a34a',
    bgRgb: 'rgba(22, 163, 74, 0.15)',
    icon: '🫑',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Wicking Bed', 'Polyculture Bed'],
    companionLikes: ['Basil', 'Marigold', 'Tomato', 'Carrot', 'Onion'],
    companionDislikes: ['Beans', 'Fennel'],
    benefits: 'Dense foliage shelters soil; pairs with basil to enhance flavor and repel thrips.',
    description: 'High-value vegetable crop with thick crisp walls; loves well-drained fertile compost.',
  },
  {
    id: 'spinach',
    name: 'Spinach (Palak)',
    category: 'Vegetables',
    scientificName: 'Spinacia oleracea',
    spacingCm: 15,
    durationMonths: 2,
    color: '#166534',
    bgRgb: 'rgba(22, 101, 52, 0.15)',
    icon: '🥬',
    waterNeed: 'High',
    idealBedTypes: ['Raised Bed', 'Wicking Bed', 'Keyhole Bed'],
    companionLikes: ['Strawberry', 'Radish', 'Cabbage', 'Cauliflower', 'Beans'],
    companionDislikes: [],
    benefits: 'Quick groundcover leaf canopy reduces evaporation and provides continuous cuttings.',
    description: 'Iron-rich leafy green; fast 30-day turnaround, perfect filler crop between slower vegetables.',
  },
  {
    id: 'okra',
    name: 'Okra (Bhindi)',
    category: 'Vegetables',
    scientificName: 'Abelmoschus esculentus',
    spacingCm: 45,
    durationMonths: 4,
    color: '#22c55e',
    bgRgb: 'rgba(34, 197, 94, 0.15)',
    icon: '🫘',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Sunken Bed'],
    companionLikes: ['Chilli', 'Brinjal', 'Tomato', 'Cucumber', 'Basil'],
    companionDislikes: [],
    benefits: 'Sturdy upright stem anchors border edges; hibiscus-like flowers attract bees.',
    description: 'Warm-season heat lover; prolific continuous pod producer with high market demand.',
  },
  {
    id: 'ginger',
    name: 'Ginger (Adrak)',
    category: 'Vegetables',
    scientificName: 'Zingiber officinale',
    spacingCm: 25,
    durationMonths: 9,
    color: '#ca8a04',
    bgRgb: 'rgba(202, 138, 4, 0.15)',
    icon: '🫚',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Food Forest Patch', 'Wicking Bed'],
    companionLikes: ['Banana', 'Papaya', 'Turmeric', 'Coconut', 'Mango'],
    companionDislikes: [],
    benefits: 'Partial shade lover; maximizes understory yield beneath banana and fruit tree canopies.',
    description: 'High-value cash rhizome; thrives in loose rich organic humus with mulching.',
  },
  {
    id: 'turmeric',
    name: 'Turmeric (Haldi)',
    category: 'Vegetables',
    scientificName: 'Curcuma longa',
    spacingCm: 30,
    durationMonths: 9,
    color: '#ea580c',
    bgRgb: 'rgba(234, 88, 12, 0.15)',
    icon: '🫚',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Food Forest Patch', 'Terrace Bed'],
    companionLikes: ['Banana', 'Papaya', 'Ginger', 'Fruit Trees', 'Chilli'],
    companionDislikes: [],
    benefits: 'Natural soil sanitizer; curcumoids deter root pathogens and subterranean insects.',
    description: 'Golden medicinal rhizome; excellent shade companion in multilayer agroforestry systems.',
  },

  // ─── Herbs ─────────────────────────────────────────────────────────────────
  {
    id: 'tulsi',
    name: 'Tulsi (Holy Basil)',
    category: 'Herbs',
    scientificName: 'Ocimum sanctum',
    spacingCm: 35,
    durationMonths: 12,
    color: '#047857',
    bgRgb: 'rgba(4, 120, 87, 0.15)',
    icon: '🌿',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Keyhole Bed', 'Polyculture Bed', 'Food Forest Patch'],
    companionLikes: ['Tomato', 'Chilli', 'Brinjal', 'Fruit Trees'],
    companionDislikes: ['Rue'],
    benefits: 'Sacred medicinal herb; eugenol aroma repels mosquitoes, flies, and tomato hornworms.',
    description: 'Perennial aromatic powerhouse; enhances essential oil content and flavor of neighbours.',
  },
  {
    id: 'mint',
    name: 'Mint (Pudina)',
    category: 'Herbs',
    scientificName: 'Mentha spicata',
    spacingCm: 25,
    durationMonths: 12,
    color: '#10b981',
    bgRgb: 'rgba(16, 185, 129, 0.15)',
    icon: '🍃',
    waterNeed: 'High',
    idealBedTypes: ['Sunken Bed', 'Wicking Bed', 'Food Forest Patch'],
    companionLikes: ['Cabbage', 'Cauliflower', 'Tomato', 'Brinjal'],
    companionDislikes: ['Parsley', 'Chamomile'],
    benefits: 'Spreading menthol aroma confuses cabbage loopers and aphids; acts as living mulch.',
    description: 'Fast-spreading perennial groundcover; best placed in damp zones or contained borders.',
  },
  {
    id: 'coriander',
    name: 'Coriander (Dhaniya)',
    category: 'Herbs',
    scientificName: 'Coriandrum sativum',
    spacingCm: 15,
    durationMonths: 2,
    color: '#22c55e',
    bgRgb: 'rgba(34, 197, 94, 0.15)',
    icon: '🌿',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Keyhole Bed', 'Nursery Bed'],
    companionLikes: ['Cabbage', 'Carrot', 'Tomato', 'Chilli'],
    companionDislikes: ['Fennel'],
    benefits: 'Umbel flowers attract parasitic wasps and hoverflies that devour pest larvae.',
    description: 'Aromatic cool-season culinary staple; leaves harvestable in 30 days, seeds later.',
  },
  {
    id: 'lemongrass',
    name: 'Lemongrass',
    category: 'Herbs',
    scientificName: 'Cymbopogon citratus',
    spacingCm: 60,
    durationMonths: 24,
    color: '#a3e635',
    bgRgb: 'rgba(163, 230, 53, 0.15)',
    icon: '🌾',
    waterNeed: 'Low',
    idealBedTypes: ['Terrace Bed', 'Food Forest Patch', 'Raised Bed'],
    companionLikes: ['Fruit Trees', 'Tomato', 'Chilli', 'Ginger', 'Haldi'],
    companionDislikes: [],
    benefits: 'Citronella root and foliage oil repels nematodes, ticks, and burrowing insects.',
    description: 'Stately clumping grass that anchors slope edges and provides continuous aromatic mulching material.',
  },
  {
    id: 'sweet_basil',
    name: 'Sweet Basil',
    category: 'Herbs',
    scientificName: 'Ocimum basilicum',
    spacingCm: 30,
    durationMonths: 6,
    color: '#16a34a',
    bgRgb: 'rgba(22, 163, 74, 0.15)',
    icon: '🌿',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Wicking Bed'],
    companionLikes: ['Tomato', 'Chilli', 'Capsicum', 'Brinjal', 'Garlic'],
    companionDislikes: ['Rue'],
    benefits: 'Essential companion for Tomatoes; improves tomato sweetness and repels thrips.',
    description: 'Classic culinary herb with rich sweet aroma; thrives with regular pinch harvesting.',
  },
  {
    id: 'aloe_vera',
    name: 'Aloe Vera (Ghritkumari)',
    category: 'Herbs',
    scientificName: 'Aloe barbadensis miller',
    spacingCm: 45,
    durationMonths: 36,
    color: '#059669',
    bgRgb: 'rgba(5, 150, 105, 0.15)',
    icon: '🪴',
    waterNeed: 'Low',
    idealBedTypes: ['Terrace Bed', 'Raised Bed', 'Keyhole Bed'],
    companionLikes: ['Fruit Trees', 'Herbs', 'Onion'],
    companionDislikes: [],
    benefits: 'Drought-hardy succulent; gel acts as natural root stimulator for new plant cuttings.',
    description: 'Medicinal powerhouse requiring zero maintenance; thrives on dry borders and slope edges.',
  },

  // ─── Fruit Crops ───────────────────────────────────────────────────────────
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruit Crops',
    scientificName: 'Musa acuminata',
    spacingCm: 200,
    durationMonths: 12,
    color: '#eab308',
    bgRgb: 'rgba(234, 179, 8, 0.15)',
    icon: '🍌',
    waterNeed: 'High',
    idealBedTypes: ['Food Forest Patch', 'Sunken Bed', 'Hugelkultur Bed'],
    companionLikes: ['Papaya', 'Ginger', 'Haldi', 'Lemongrass', 'Sweet Potato'],
    companionDislikes: [],
    benefits: 'Giant herbaceous pseudostem creates moist, cool understory microclimate for rhizomes.',
    description: 'Rapid biomass generator; thrives near greywater swales and organic waste trenches.',
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'Fruit Crops',
    scientificName: 'Carica papaya',
    spacingCm: 180,
    durationMonths: 18,
    color: '#f97316',
    bgRgb: 'rgba(249, 115, 22, 0.15)',
    icon: '🍈',
    waterNeed: 'Moderate',
    idealBedTypes: ['Food Forest Patch', 'Raised Bed', 'Hugelkultur Bed'],
    companionLikes: ['Haldi', 'Ginger', 'Banana', 'Beans', 'Cowpea'],
    companionDislikes: [],
    benefits: 'Vertical canopy allows sunlight to penetrate while sheltering shade-tolerant crops below.',
    description: 'Core pillar of Chhattisgarh multilayer natural farming; prolific yielder in Year 2.',
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    category: 'Fruit Crops',
    scientificName: 'Ananas comosus',
    spacingCm: 60,
    durationMonths: 18,
    color: '#ca8a04',
    bgRgb: 'rgba(202, 138, 4, 0.15)',
    icon: '🍍',
    waterNeed: 'Low',
    idealBedTypes: ['Terrace Bed', 'Food Forest Patch', 'Raised Bed'],
    companionLikes: ['Banana', 'Papaya', 'Ginger', 'Turmeric', 'Coconut'],
    companionDislikes: [],
    benefits: 'Drought-hardy bromeliad with serrated leaves that form living barriers against pests.',
    description: 'High-value perennial ground crop; thrives under dappled tree canopies.',
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate (Anaar)',
    category: 'Fruit Crops',
    scientificName: 'Punica granatum',
    spacingCm: 350,
    canopyDiameterM: 3.5,
    durationMonths: 36,
    color: '#e11d48',
    bgRgb: 'rgba(225, 29, 72, 0.15)',
    icon: '🍎',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch', 'Terrace Bed'],
    companionLikes: ['Marigold', 'Mint', 'Garlic', 'Vetiver', 'Basil'],
    companionDislikes: [],
    benefits: 'Extremely drought-tolerant; high antioxidant fruit with premium commercial value.',
    description: 'Bushy multi-stemmed fruit tree; thrives in semi-arid conditions with organic mulch.',
  },

  // ─── Trees ─────────────────────────────────────────────────────────────────
  {
    id: 'mango',
    name: 'Mango',
    category: 'Trees',
    scientificName: 'Mangifera indica',
    spacingCm: 800,
    canopyDiameterM: 8.0,
    durationMonths: 120,
    color: '#d97706',
    bgRgb: 'rgba(217, 119, 6, 0.15)',
    icon: '🥭',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['Moringa', 'Vetiver', 'Lemongrass', 'Ginger', 'Haldi', 'Cowpea'],
    companionDislikes: ['Potato'],
    benefits: 'Grand canopy tree; deep taproots mine subsoil minerals and deposit nutrient-rich leaf mulch.',
    description: 'King of Indian fruits; long-lived anchor for agroforestry boundary and food forest systems.',
  },
  {
    id: 'guava',
    name: 'Guava (Amrood)',
    category: 'Trees',
    scientificName: 'Psidium guajava',
    spacingCm: 400,
    canopyDiameterM: 4.5,
    durationMonths: 60,
    color: '#84cc16',
    bgRgb: 'rgba(132, 204, 22, 0.15)',
    icon: '🍏',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['Papaya', 'Marigold', 'Beans', 'Coriander', 'Garlic'],
    companionDislikes: [],
    benefits: 'Fast-bearing small tree; flowering attracts honeybees and pollinator insects in swarms.',
    description: 'Extremely resilient to poor soils and droughts; provides 2 heavy fruit harvests annually.',
  },
  {
    id: 'moringa',
    name: 'Moringa (Drumstick / Munaga)',
    category: 'Trees',
    scientificName: 'Moringa oleifera',
    spacingCm: 300,
    canopyDiameterM: 3.5,
    durationMonths: 36,
    color: '#16a34a',
    bgRgb: 'rgba(22, 163, 74, 0.15)',
    icon: '🌿',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch', 'Raised Bed'],
    companionLikes: ['Mango', 'Guava', 'Tomato', 'Chilli', 'Papaya'],
    companionDislikes: [],
    benefits: 'Miracle tree with high leaf nitrogen; coppicing yields abundant green manure and protein pods.',
    description: 'Rapid growth (up to 3m in year 1); lightweight open canopy allows full undercrop growth.',
  },
  {
    id: 'lemon',
    name: 'Lemon (Nimbu)',
    category: 'Trees',
    scientificName: 'Citrus limon',
    spacingCm: 350,
    canopyDiameterM: 3.5,
    durationMonths: 48,
    color: '#facc15',
    bgRgb: 'rgba(250, 204, 21, 0.15)',
    icon: '🍋',
    waterNeed: 'Moderate',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['Marigold', 'Mint', 'Garlic', 'Basil', 'Sesbania'],
    companionDislikes: ['Walnut'],
    benefits: 'Citrus blossoms produce nectar for predatory insects; thorny branches deter stray livestock.',
    description: 'High continuous cashflow crop; fits perfectly in understory zones of larger fruit groves.',
  },
  {
    id: 'coconut',
    name: 'Coconut',
    category: 'Trees',
    scientificName: 'Cocos nucifera',
    spacingCm: 750,
    canopyDiameterM: 6.5,
    durationMonths: 240,
    color: '#0d9488',
    bgRgb: 'rgba(13, 148, 136, 0.15)',
    icon: '🥥',
    waterNeed: 'High',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['Banana', 'Pineapple', 'Haldi', 'Ginger', 'Black Pepper', 'Cocoa'],
    companionDislikes: [],
    benefits: 'Tall crown allows 100% intercropping of multilayer shade crops and pepper vines on trunks.',
    description: 'Perennial tree providing round-the-year water, oil, fiber, and organic coir mulch.',
  },
  {
    id: 'jackfruit',
    name: 'Jackfruit (Kathal)',
    category: 'Trees',
    scientificName: 'Artocarpus heterophyllus',
    spacingCm: 900,
    canopyDiameterM: 9.0,
    durationMonths: 180,
    color: '#65a30d',
    bgRgb: 'rgba(101, 163, 13, 0.15)',
    icon: '🍈',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['Black Pepper', 'Coffee', 'Turmeric', 'Ginger', 'Lemongrass'],
    companionDislikes: [],
    benefits: 'Massive windbreak tree; thick organic leaf fall creates dense humus layer over time.',
    description: 'Giant multi-purpose tree; massive drought-tolerant fruits harvested green as vegetable or ripe.',
  },
  {
    id: 'neem',
    name: 'Neem',
    category: 'Trees',
    scientificName: 'Azadirachta indica',
    spacingCm: 800,
    canopyDiameterM: 7.5,
    durationMonths: 360,
    color: '#15803d',
    bgRgb: 'rgba(21, 128, 61, 0.15)',
    icon: '🌳',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['All Crops & Trees'],
    companionDislikes: [],
    benefits: 'Natural bio-pesticide tree; azadirachtin in leaves and seeds repels 200+ agricultural pests.',
    description: 'Sacred guardian tree of organic farms; leaves used for Agniastra and Dashparni pest decoctions.',
  },
  {
    id: 'amla',
    name: 'Amla (Indian Gooseberry)',
    category: 'Trees',
    scientificName: 'Phyllanthus emblica',
    spacingCm: 450,
    canopyDiameterM: 4.5,
    durationMonths: 60,
    color: '#84cc16',
    bgRgb: 'rgba(132, 204, 22, 0.15)',
    icon: '🫒',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch'],
    companionLikes: ['Turmeric', 'Ginger', 'Marigold', 'Vetiver'],
    companionDislikes: [],
    benefits: 'Feather-light canopy allows good sunlight filtering for ground crops; heavy Vitamin C yielder.',
    description: 'Hardy medicinal fruit tree with tremendous commercial longevity and zero pest issues.',
  },

  // ─── Support Plants ────────────────────────────────────────────────────────
  {
    id: 'marigold',
    name: 'Marigold (Genda)',
    category: 'Support Plants',
    scientificName: 'Tagetes erecta',
    spacingCm: 30,
    durationMonths: 4,
    color: '#f59e0b',
    bgRgb: 'rgba(245, 158, 11, 0.15)',
    icon: '🌼',
    waterNeed: 'Low',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Keyhole Bed', 'Terrace Bed'],
    companionLikes: ['Tomato', 'Chilli', 'Brinjal', 'Potato', 'Fruit Trees'],
    companionDislikes: ['Beans', 'Cabbage'],
    benefits: 'Roots secrete alpha-terthienyl that kills harmful root-knot nematodes; flowers attract ladybugs.',
    description: 'The supreme organic bio-protection flower; planted at corner points of all vegetable beds.',
  },
  {
    id: 'vetiver',
    name: 'Vetiver (Khus)',
    category: 'Support Plants',
    scientificName: 'Chrysopogon zizanioides',
    spacingCm: 20,
    durationMonths: 36,
    color: '#15803d',
    bgRgb: 'rgba(21, 128, 61, 0.15)',
    icon: '🌾',
    waterNeed: 'Low',
    idealBedTypes: ['Terrace Bed', 'Food Forest Patch'],
    companionLikes: ['All Fruit Trees', 'Vegetables on Slopes'],
    companionDislikes: [],
    benefits: 'Deep 3-meter sponge root matrix locks soil, prevents bund collapse, and purifies groundwater.',
    description: 'Super-hardy sterile hedge grass essential for soil conservation and biomass production.',
  },
  {
    id: 'sunflower',
    name: 'Sunflower (Surajmukhi)',
    category: 'Support Plants',
    scientificName: 'Helianthus annuus',
    spacingCm: 45,
    durationMonths: 3,
    color: '#eab308',
    bgRgb: 'rgba(234, 179, 8, 0.15)',
    icon: '🌻',
    waterNeed: 'Moderate',
    idealBedTypes: ['Raised Bed', 'Polyculture Bed', 'Hugelkultur Bed'],
    companionLikes: ['Cucumber', 'Corn', 'Beans', 'Pumpkin', 'Squash'],
    companionDislikes: ['Potato'],
    benefits: 'Heavy pollinator magnet; acts as physical trellis for light climbing beans and attracts beneficial birds.',
    description: 'Stunning solar biomonitor; deep taproot extracts stubborn subsoil minerals.',
  },
  {
    id: 'sesbania',
    name: 'Sesbania (Dhaincha)',
    category: 'Support Plants',
    scientificName: 'Sesbania bispinosa',
    spacingCm: 20,
    durationMonths: 2,
    color: '#10b981',
    bgRgb: 'rgba(16, 185, 129, 0.15)',
    icon: '🌿',
    waterNeed: 'Low',
    idealBedTypes: ['Raised Bed', 'Sunken Bed', 'Food Forest Patch'],
    companionLikes: ['Rice', 'Sugarcane', 'Cotton', 'Fruit Trees'],
    companionDislikes: [],
    benefits: 'Fastest growing green manure legume; fixes up to 100 kg nitrogen per acre in 50 days.',
    description: 'Pre-season cover crop slashed down before main bed planting to create rich fertile soil tilth.',
  },
  {
    id: 'gliricidia',
    name: 'Gliricidia (Quick Stick)',
    category: 'Support Plants',
    scientificName: 'Gliricidia sepium',
    spacingCm: 100,
    durationMonths: 60,
    color: '#059669',
    bgRgb: 'rgba(5, 150, 105, 0.15)',
    icon: '🌳',
    waterNeed: 'Low',
    idealBedTypes: ['Food Forest Patch', 'Terrace Bed'],
    companionLikes: ['All Fruit Trees', 'Crops needing green manure'],
    companionDislikes: [],
    benefits: 'Live fencing tree whose leaves provide premium high-nitrogen organic compost and Jeevamrit biomass.',
    description: 'Easy living fence tree grown from simple cuttings along farm boundaries.',
  },
];

export const FARM_ELEMENTS_CATALOGUE: FarmElementDefinition[] = [
  // ─── Water Elements ─────────────────────────────────────────────────────────
  {
    type: 'pond',
    name: 'Farm Pond / Water Body',
    category: 'water',
    defaultWidthM: 10,
    defaultHeightM: 8,
    default3DHeightM: -1.5,
    color: '#0284c7', // sky-600
    iconName: 'Waves',
    icon: '🌊',
    description: 'Rainwater harvesting farm pond lined with natural clay/bentonite to recharge groundwater.',
  },
  {
    type: 'tank',
    name: 'Water Storage Tank',
    category: 'water',
    defaultWidthM: 4,
    defaultHeightM: 4,
    default3DHeightM: 2.5,
    color: '#0369a1', // sky-700
    iconName: 'Cylinder',
    icon: '🛢️',
    description: 'Elevated overhead water tank for gravity-fed drip and sprinkler irrigation lines.',
  },
  {
    type: 'swale',
    name: 'Contour Swale / Trench',
    category: 'water',
    defaultWidthM: 14,
    defaultHeightM: 2,
    default3DHeightM: -0.5,
    color: '#0891b2', // cyan-600
    iconName: 'Spline',
    icon: '〰️',
    description: 'On-contour ditch and berm to slow, spread, and sink surface runoff across the farm landscape.',
  },
  {
    type: 'irrigation_line',
    name: 'Main Irrigation Line',
    category: 'water',
    defaultWidthM: 16,
    defaultHeightM: 1,
    default3DHeightM: 0.2,
    color: '#2563eb', // blue-600
    iconName: 'GitCommit',
    icon: '💧',
    description: 'Sub-surface HDPE mainline delivering pressurized water to zone valves and drip manifolds.',
  },

  // ─── Infrastructure ────────────────────────────────────────────────────────
  {
    type: 'pathway',
    name: 'Farm Pathway / Road',
    category: 'infrastructure',
    defaultWidthM: 12,
    defaultHeightM: 2.5,
    default3DHeightM: 0.05,
    color: '#a8a29e', // stone-400
    iconName: 'Footprints',
    icon: '🛤️',
    description: 'Hard-packed gravel or rammed earth accessway for wheelbarrows, workers, and mini-tractors.',
  },
  {
    type: 'fence',
    name: 'Perimeter Fence / Bio-Hedge',
    category: 'infrastructure',
    defaultWidthM: 20,
    defaultHeightM: 1,
    default3DHeightM: 1.8,
    color: '#78716c', // stone-500
    iconName: 'Shield',
    icon: '🧱',
    description: 'Protective boundary fence or thorny bio-hedge keeping wild animals and stray cattle out.',
  },
  {
    type: 'gate',
    name: 'Entry Gate',
    category: 'infrastructure',
    defaultWidthM: 4,
    defaultHeightM: 1,
    default3DHeightM: 2.2,
    color: '#57534e', // stone-600
    iconName: 'DoorOpen',
    icon: '🚪',
    description: 'Reinforced farm vehicle and equipment entrance gate.',
  },
  {
    type: 'shed',
    name: 'Tool & Equipment Shed',
    category: 'infrastructure',
    defaultWidthM: 6,
    defaultHeightM: 4,
    default3DHeightM: 3.0,
    color: '#b45309', // amber-700
    iconName: 'Home',
    icon: '🏚️',
    description: 'Secure farm outbuilding storing tools, seeds, harvested produce, and spraying equipment.',
  },
  {
    type: 'greenhouse',
    name: 'Greenhouse / Polyhouse',
    category: 'infrastructure',
    defaultWidthM: 10,
    defaultHeightM: 6,
    default3DHeightM: 3.8,
    color: '#38bdf8', // sky-400
    iconName: 'Sparkles',
    icon: '🛖',
    description: 'Climate-controlled UV polyethylene shelter for seedling germination and high-value vegetables.',
  },
  {
    type: 'compost_area',
    name: 'Compost & Jeevamrit Unit',
    category: 'infrastructure',
    defaultWidthM: 6,
    defaultHeightM: 4,
    default3DHeightM: 1.2,
    color: '#854d0e', // yellow-800
    iconName: 'Recycle',
    icon: '♻️',
    description: 'Dedicated processing yard for Jeevamrit fermentation barrels, Ghanjeevamrit, and vermicompost pits.',
  },

  // ─── Animal Systems ────────────────────────────────────────────────────────
  {
    type: 'cow_shed',
    name: 'Desi Cow Shelter (Gaushala)',
    category: 'animal',
    defaultWidthM: 8,
    defaultHeightM: 6,
    default3DHeightM: 3.2,
    color: '#92400e', // amber-800
    iconName: 'Warehouse',
    icon: '🐄',
    description: 'Indigenous cow shed equipped with urine-collection channels essential for ZBNF formulations.',
  },
  {
    type: 'chicken_coop',
    name: 'Pastured Poultry Coop',
    category: 'animal',
    defaultWidthM: 5,
    defaultHeightM: 4,
    default3DHeightM: 2.4,
    color: '#c2410c', // orange-700
    iconName: 'Egg',
    icon: '🐔',
    description: 'Mobile or fixed poultry coop; chickens forage pests, weed seeds, and scratch fertilize bed plots.',
  },
  {
    type: 'goat_shelter',
    name: 'Goat Shelter',
    category: 'animal',
    defaultWidthM: 6,
    defaultHeightM: 4,
    default3DHeightM: 2.6,
    color: '#a16207', // yellow-700
    iconName: 'ShieldAlert',
    icon: '🐐',
    description: 'Elevated slatted floor shelter protecting small ruminants and collecting concentrated organic manure pellets.',
  },
];

/**
 * Calculates companion planting synergy score between a list of crops placed in the same bed.
 */
export const calculateBedSynergy = (crops: { cropName: string }[]): { score: number; synergies: string[]; conflicts: string[] } => {
  if (!crops || crops.length <= 1) {
    return { score: 100, synergies: [], conflicts: [] };
  }

  const synergies: string[] = [];
  const conflicts: string[] = [];
  const names = crops.map((c) => c.cropName);

  for (let i = 0; i < crops.length; i++) {
    const cropA = CROP_LIBRARY.find((c) => c.name.toLowerCase() === names[i].toLowerCase());
    if (!cropA) continue;

    for (let j = i + 1; j < crops.length; j++) {
      const cropB = CROP_LIBRARY.find((c) => c.name.toLowerCase() === names[j].toLowerCase());
      if (!cropB) continue;

      // Check if A likes B or B likes A
      const aLikesB = cropA.companionLikes.some((like) => like.toLowerCase().includes(cropB.name.toLowerCase()) || cropB.name.toLowerCase().includes(like.toLowerCase()));
      const bLikesA = cropB.companionLikes.some((like) => like.toLowerCase().includes(cropA.name.toLowerCase()) || cropA.name.toLowerCase().includes(like.toLowerCase()));

      if (aLikesB || bLikesA) {
        synergies.push(`${cropA.name} + ${cropB.name} (Beneficial companions)`);
      }

      // Check if A dislikes B or B dislikes A
      const aDislikesB = cropA.companionDislikes.some((dislike) => dislike.toLowerCase().includes(cropB.name.toLowerCase()) || cropB.name.toLowerCase().includes(dislike.toLowerCase()));
      const bDislikesA = cropB.companionDislikes.some((dislike) => dislike.toLowerCase().includes(cropA.name.toLowerCase()) || cropA.name.toLowerCase().includes(dislike.toLowerCase()));

      if (aDislikesB || bDislikesA) {
        conflicts.push(`${cropA.name} + ${cropB.name} (Avoid planting together)`);
      }
    }
  }

  let score = 80;
  score += synergies.length * 10;
  score -= conflicts.length * 25;
  score = Math.max(10, Math.min(100, score));

  return { score, synergies, conflicts };
};
