import prisma from "../../src/config/prisma.js";
import { fileURLToPath } from "node:url";

// All agronomic values are tuned for Chhattisgarh conditions.
// Experts can update individual crop fields via the Expert Panel without re-seeding.
export const CROP_ROWS = [
  {
    name:                               "Rice",
    scientificName:                     "Oryza sativa",
    suitableSoilTypes:                  ["Kanhar", "Dorsa"],
    minPh:                              5.5,
    maxPh:                              6.5,
    season:                             "Kharif",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 14000,
    preferredDrainage:                  "Slow",      // needs standing water
    plantingWindowStart:                6,            // June
    plantingWindowEnd:                  7,            // July
    minTempC:                           20,
    maxTempC:                           37,
    rainfallTolerance:                  "water-loving",
    minSoilHealthScore:                 30,
    seasonDurationWeeks:                17,
    cropFamily:                         "Cereal",
    riskLevel:                          "intermediate",
  },
  {
    name:                               "Cotton",
    scientificName:                     "Gossypium hirsutum",
    suitableSoilTypes:                  ["Kanhar"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Kharif",
    estimatedDurationMonths:            6,
    weeklyWaterRequirementLitersPerAcre: 7000,
    preferredDrainage:                  "Fast",       // dies in waterlogged soil
    plantingWindowStart:                5,            // May
    plantingWindowEnd:                  6,            // June
    minTempC:                           21,
    maxTempC:                           37,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 50,
    seasonDurationWeeks:                26,
  },
  {
    name:                               "Wheat",
    scientificName:                     "Triticum aestivum",
    suitableSoilTypes:                  ["Kanhar"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Rabi",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 5500,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                10,           // October
    plantingWindowEnd:                  11,           // November
    minTempC:                           10,
    maxTempC:                           25,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 40,
    seasonDurationWeeks:                17,
  },
  {
    name:                               "Gram",
    scientificName:                     "Cicer arietinum",
    suitableSoilTypes:                  ["Kanhar"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Rabi",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 3500,
    preferredDrainage:                  "Fast",       // sensitive to waterlogging
    plantingWindowStart:                10,
    plantingWindowEnd:                  11,
    minTempC:                           10,
    maxTempC:                           25,
    rainfallTolerance:                  "drought-tolerant",
    minSoilHealthScore:                 20,
    seasonDurationWeeks:                17,
  },
  {
    name:                               "Millets",
    scientificName:                     "Pennisetum glaucum",
    suitableSoilTypes:                  ["Matasi", "Bhata"],
    minPh:                              6.0,
    maxPh:                              7.5,
    season:                             "Kharif",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 3000,
    preferredDrainage:                  "Fast",       // extremely drought-hardy
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           25,
    maxTempC:                           38,
    rainfallTolerance:                  "drought-tolerant",
    minSoilHealthScore:                 10,
    seasonDurationWeeks:                17,
  },
  {
    name:                               "Groundnut",
    scientificName:                     "Arachis hypogaea",
    suitableSoilTypes:                  ["Matasi"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Kharif",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 4500,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           22,
    maxTempC:                           33,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 30,
    seasonDurationWeeks:                17,
  },
  {
    name:                               "Pulses",
    scientificName:                     "Cajanus cajan",
    suitableSoilTypes:                  ["Matasi"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Rabi",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 3500,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                10,
    plantingWindowEnd:                  11,
    minTempC:                           15,
    maxTempC:                           30,
    rainfallTolerance:                  "drought-tolerant",
    minSoilHealthScore:                 20,
    seasonDurationWeeks:                17,
  },
  {
    name:                               "Maize",
    scientificName:                     "Zea mays",
    suitableSoilTypes:                  ["Dorsa", "Bhata"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Kharif",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 6000,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           18,
    maxTempC:                           35,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 35,
    seasonDurationWeeks:                17,
  },
  {
    name:                               "Vegetables",
    scientificName:                     null,
    suitableSoilTypes:                  ["Dorsa"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Zaid",
    estimatedDurationMonths:            3,
    weeklyWaterRequirementLitersPerAcre: 7500,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                2,            // February
    plantingWindowEnd:                  3,            // March
    minTempC:                           15,
    maxTempC:                           30,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 40,
    seasonDurationWeeks:                13,
  },
  {
    name:                               "Tuber crops",
    scientificName:                     null,
    suitableSoilTypes:                  ["Bhata"],
    minPh:                              6.0,
    maxPh:                              7.0,
    season:                             "Rabi",
    estimatedDurationMonths:            5,
    weeklyWaterRequirementLitersPerAcre: 6500,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                10,
    plantingWindowEnd:                  11,
    minTempC:                           20,
    maxTempC:                           30,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 25,
    seasonDurationWeeks:                22,
  },
  {
    name:                               "Moong",
    scientificName:                     "Vigna radiata",
    minPh:                              6.0,
    maxPh:                              7.5,
    season:                             "Kharif",
    estimatedDurationMonths:            2,
    weeklyWaterRequirementLitersPerAcre: 3500,
    preferredDrainage:                  "Fast",
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           25,
    maxTempC:                           40,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 20,
    seasonDurationWeeks:                10,
    seedKgPerAcre:                      8,
    spacingNotes:                       "30 cm row, 10 cm plant",
    suitableSoilTypes:                  ["Matasi", "Dorsa"],
  },
  {
    name:                               "Soybean",
    scientificName:                     "Glycine max",
    minPh:                              6.0,
    maxPh:                              7.5,
    season:                             "Kharif",
    estimatedDurationMonths:            4,
    weeklyWaterRequirementLitersPerAcre: 4500,
    preferredDrainage:                  "Balanced",
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           20,
    maxTempC:                           35,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 25,
    seasonDurationWeeks:                16,
    seedKgPerAcre:                      30,
    spacingNotes:                       "45 cm row, 5 cm plant",
    suitableSoilTypes:                  ["Kanhar", "Dorsa", "Matasi"],
  },
  {
    name:                               "Tur/Arhar",
    scientificName:                     "Cajanus cajan",
    minPh:                              6.0,
    maxPh:                              7.5,
    season:                             "Kharif",
    estimatedDurationMonths:            6,
    weeklyWaterRequirementLitersPerAcre: 3000,
    preferredDrainage:                  "Fast",
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           20,
    maxTempC:                           40,
    rainfallTolerance:                  "drought-tolerant",
    minSoilHealthScore:                 20,
    seasonDurationWeeks:                24,
    seedKgPerAcre:                      5,
    spacingNotes:                       "75 cm row, 30 cm plant",
    suitableSoilTypes:                  ["Matasi", "Bhata", "Dorsa"],
  },
  {
    name:                               "Urad",
    scientificName:                     "Vigna mungo",
    minPh:                              6.0,
    maxPh:                              7.5,
    season:                             "Kharif",
    estimatedDurationMonths:            2,
    weeklyWaterRequirementLitersPerAcre: 3000,
    preferredDrainage:                  "Fast",
    plantingWindowStart:                6,
    plantingWindowEnd:                  7,
    minTempC:                           25,
    maxTempC:                           40,
    rainfallTolerance:                  "moderate",
    minSoilHealthScore:                 20,
    seasonDurationWeeks:                10,
    seedKgPerAcre:                      10,
    spacingNotes:                       "30 cm row, 10 cm plant",
    suitableSoilTypes:                  ["Matasi", "Dorsa"],
  },
];

export const seedCrops = async () => {
  await prisma.crop.deleteMany();
  await prisma.crop.createMany({ data: CROP_ROWS });
};

const isDirectRun = process.argv[1] === fileURLToPath(import.meta.url);

if (isDirectRun) {
  seedCrops()
    .then(async () => {
      console.log(`Seeded ${CROP_ROWS.length} crop rules.`);
      await prisma.$disconnect();
    })
    .catch(async (error) => {
      console.error("Failed to seed crop rules:", error);
      await prisma.$disconnect();
      process.exit(1);
    });
}
